service: event-101-producer-ci-cd

frameworkVersion: '3'

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!*/**"


provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: arn:aws:dynamodb:us-east-1:357535579452:table/event101Table
        - Effect: Allow
          Action:
            - "events:PutEvents"
          Resource: 'arn:aws:events:us-east-1:357535579452:event-bus/CentralBus'


functions:
  ingest-event:
    handler: ingest_event/handler.ingest_event
    package:
      patterns:
        - "ingest_event/*"
        - "ingest_event/utils/*"
    events:
      - http:
          path: ingest_event101
          method: POST
          request:
            schemas:
              application/json: ${file(schemas/event-101-schema.json)}


resources:
  Resources:
    event101Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: event101Table
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


plugins:
  - serverless-python-requirements